name: CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Docker Build
        run: docker build -t devops-ai-api:latest -f ./docker/Dockerfile .
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Set up kubeconfig
        run: az aks get-credentials --resource-group <RESOURCE_GROUP> --name <CLUSTER_NAME>
      - name: Helm Deploy
        run: helm upgrade --install devops-api ./helm/devops-api -f ./helm/devops-api/values.yaml
